trigger_dict = {
                1: "Instructions_Displayed",
                2: "Rest_Start",
                3: "Rest_End",
                4: "Finger_Tapping_right_120",
                5: "Finger_Tapping_right_80",
                6: "Finger_Tapping_left_120",
                7: "Finger_Tapping_left_80",
                8: "Finger_Tapping_both_120",
                9: "Finger_Tapping_both_80",
                10: "Task_End",
                11: "Breath_Holding_in",
                12: "Breath_Holding_out",
                13: "Breath_Holdinging_hyper",
                14: "Startle_glass",
                15: "Startle_event",
                16: "Stroop_Block_Start",
                17: "Stroop_Block_End",
                18: "Stroop_Stim_Displayed_Congruent",
                19: "Stroop_Stim_Displayed_Incongruent",
                20: "Stroop_Stim_Response_Correct",
                21: "Stroop_Stim_Response_Incorrect"
               }


trigger_string_dict = {
                        "Instructions_Displayed": 1,
                        "Rest_Start": 2,
                        "Rest_End": 3,
                        "Finger_Tapping_right_120": 4,
                        "Finger_Tapping_right_80": 5,
                        "Finger_Tapping_left_120": 6,
                        "Finger_Tapping_left_80": 7,
                        "Finger_Tapping_both_120": 8,
                        "Finger_Tapping_both_80": 9,
                        "Task_End": 10,
                        "Breath_Holding_in": 11,
                        "Breath_Holding_out": 12,
                        "Breath_Holding_hyper": 13,
                        "Startle_glass": 14,
                        "Startle_event": 15,
                        "Stroop_Block_Start": 16,
                        "Stroop_Block_End": 17,
                        "Stroop_Stim_Displayed_Congruent": 18,
                        "Stroop_Stim_Displayed_Incongruent": 19,
                        "Stroop_Stim_Response_Correct": 20,
                        "Stroop_Stim_Response_Incorrect": 21
                      }
